
version: "3"

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5430:5432
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    command: ["postgres", "-c", "log_statement=all"]

volumes:
  pg_data:
